-- V1: esquema base do AutoSystem (escopo aprovado: veiculos, clientes, vendas).
-- Tipos e constraints seguem docs/09 (MER) e o DER.
-- Limites dinamicos (ano <= ano atual + 1, data_venda nao futura) sao validados na
-- APLICACAO, nao no banco, para manter os CHECK imutaveis (boa pratica PostgreSQL).

CREATE TABLE veiculos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca         VARCHAR(50)   NOT NULL,
    modelo        VARCHAR(50)   NOT NULL,
    ano           SMALLINT      NOT NULL CHECK (ano >= 1950),
    cor           VARCHAR(30)   NOT NULL,
    quilometragem INTEGER       NOT NULL CHECK (quilometragem >= 0),
    preco         NUMERIC(12,2) NOT NULL CHECK (preco > 0),
    placa         VARCHAR(7),
    status        VARCHAR(20)   NOT NULL DEFAULT 'disponivel'
                  CHECK (status IN ('disponivel', 'reservado', 'vendido')),
    criado_em     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE clientes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100) NOT NULL,
    cpf           CHAR(11)     NOT NULL UNIQUE,
    telefone      VARCHAR(20)  NOT NULL,
    email         VARCHAR(100),
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE vendas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id  BIGINT        NOT NULL REFERENCES veiculos(id) ON DELETE RESTRICT,
    cliente_id  BIGINT        NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
    vendedor    VARCHAR(100)  NOT NULL,
    valor_venda NUMERIC(12,2) NOT NULL CHECK (valor_venda > 0),
    data_venda  DATE          NOT NULL,
    criado_em   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- "veiculo vendido nao pode ser vendido de novo"
    CONSTRAINT venda_unica_por_veiculo UNIQUE (veiculo_id)
);

-- placa unica somente quando preenchida (regra de negocio, nao otimizacao)
CREATE UNIQUE INDEX idx_veiculos_placa ON veiculos (placa)
    WHERE placa IS NOT NULL AND placa <> '';

-- indices dos filtros/ordenacoes da tela de estoque
CREATE INDEX idx_veiculos_status    ON veiculos (status);
CREATE INDEX idx_veiculos_marca     ON veiculos (marca);
CREATE INDEX idx_veiculos_preco     ON veiculos (preco);
CREATE INDEX idx_veiculos_criado_em ON veiculos (criado_em);

-- indices de vendas (historico por periodo e por cliente)
CREATE INDEX idx_vendas_data    ON vendas (data_venda DESC);
CREATE INDEX idx_vendas_cliente ON vendas (cliente_id);
