-- V2: tabela de usuarios com perfil de acesso.
-- Senha guardada como HASH (BCrypt), nunca em texto puro (requisito de seguranca do professor).
-- Perfil como VARCHAR + CHECK (nao ENUM nativo), coerente com o padrao do projeto.

CREATE TABLE usuarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    senha         VARCHAR(100) NOT NULL,
    perfil        VARCHAR(20)  NOT NULL DEFAULT 'VENDEDOR'
                  CHECK (perfil IN ('ADMIN', 'GERENTE', 'VENDEDOR')),
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_usuarios_nome ON usuarios (nome);
